Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 2
  end

  config.vm.synced_folder "./scripts", "/opt/scripts"

  config.vm.network "public_network", bridge: "en0:Ethernet" # Replace with your physical NIC name
  config.vm.network "private_network", ip: "192.168.1.20"
end
